component_names = [
    'Joystick',
    'Relay',
    'Large Microphone',
    'Small Microphone',
    'Tracking Sensor',
    'Avoidance Sensor',
    'Flame Sensor',
    'Linear Hall Effect Sensor',
    'Touch Sensor',
    'Digital Temperature Sensor',
    'Buzzer',
    'Passive Buzzer',
    'RGB LED',
    'SMD RGB',
    'Two-color LED',
    'Two-color LED 2',
    'Reed Switch',
    'Mini Reed Switch',
    'Heartbeat Sensor',
    '7-color Flash LED',
    'Laser',
    'Button',
    'Shock Sensor',
    'Rotary Encoder',
    'Light Cup',
    'Tilt Switch',
    'Ball Switch',
    'Photo Resistor',
    'Temperature and Humidity Sensor',
    'Analog Hall Effect Sensor',
    'Hall Effect Sensor',
    'TEMP 18B20 Sensor',
    'Analog Temperature Sensor',
    'IR Emitter',
    'IR Reciever',
    'Tap Module',
    'Light Blocking Module'
]

component_names.sort()